# CircleCI job to build and deploy mvn based java project.
# Author: Ramesh Doddi

description: >
  Builds maven project using JDK executor and
  deploys artifacts to specified repository.

executor: openjdk

working_directory: ~/project

parameters:
  mvn-settings-file:
    type: string
    default: ''
    description: >
      Custom mvn settings file path.
      Helpful to centralize private repos, plugin, configs.
      Example: .circleci/mvn-settings.xml

steps:
  - checkout
  - run:
      environment:
        MVN_SETTINGS_FILE: << parameters.mvn-settings-file >>
      name: Deploy mvn artifact to repository
      command: << include(scripts/build.sh) >>
  - persist_to_workspace:
      root: ~/project
      # create env paths to avoid collision of different builds.
      # dev/build, test/build, prod/build
      paths:
        - << parameters.build_env >>/service/target
        - << parameters.build_env >>/service/pom.xml
        - << parameters.build_env >>/service/Dockerfile*
  - run:
      name: "(debug) List persisted assets"
      command: find $WORKSPACE_ROOT -maxdepth 2 -type f
